// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ5IX13r6B_poP7J-uRiF2eHOI1GYXxaw',
    appId: '1:660779536213:android:e9171e81c7baa020',
    messagingSenderId: '660779536213',
    projectId: 'lyricsnigeria-210312',
    databaseURL: 'https://lyricsnigeria-210312.firebaseio.com',
    storageBucket: 'lyricsnigeria-210312.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxLeLl_BEFx3ZwTKkbJOA6wJMGNjZnU2Q',
    appId: '1:660779536213:ios:98e9ec714f0af3ed7be9dc',
    messagingSenderId: '660779536213',
    projectId: 'lyricsnigeria-210312',
    databaseURL: 'https://lyricsnigeria-210312.firebaseio.com',
    storageBucket: 'lyricsnigeria-210312.appspot.com',
    androidClientId: '660779536213-2arhdpc2jfgt99hq8ce1hbpsq9limrdm.apps.googleusercontent.com',
    iosClientId: '660779536213-vd6bcit2sjbl4pdvil3e1p1gvupkteim.apps.googleusercontent.com',
    iosBundleId: 'com.lyricsnigeria.lyricsnigeria',
  );
}
